### ISSUE TITLE
add support for compability packs

### ISSUE THREAD

**Issue by gatosardina** [JK3Y/NPS-Browser-macOS#10]
now we have FAGdec, there will be compability packs being added to 3.67+ games
i believe they willbe added to some databse, since the windows version just got updated to support downloading these packs

**Comment by JK3Y** [comment]
Thanks, i've had this in the works for a week or so. been moving to a new apt so haven't had time. Will push out a new release today with this. Thanks!

**Comment by JK3Y** [comment]
Added in commit a82b8b197f74cebfeabadc82d6363c28f3076c26
