### ISSUE TITLE
Updates: Version #

### ISSUE THREAD

**Issue by craigerskine** [JK3Y/NPS-Browser-macOS#11]
### Enhancement

Updates sidebar data point for path version #.

Some games have multiple patches and if you want the latest you need to see the version number somewhere. I've been scrubbing the TSV manually via a text editor to know which file I should download.

![multi-patch](https://user-images.githubusercontent.com/56437/43283515-bb10b660-90de-11e8-91d5-7f87dea9a4af.png)

**Comment by JK3Y** [comment]
Ok I will add this into the upcoming release w/ compat packs. Thanks for pointing this out to me, I don't use nps for updates since I get them from the vita's LiveArea.

**Comment by craigerskine** [comment]
Thanks!

I have a ton of physical games (101 so far) and I'm downloading all the digital versions via NPS. The Vita ecosystem will not let you download the patches via the LiveArea unless you have the official digital licenses... so you have to manually download the patches via NPS as well.

I suppose I could insert each game, download the patch, etc. But, I'm using SD2Vita and that would be a config/process nightmare to move the patch from the onboard storage to the SD card or use a USB drive as a temp storage. Also, games like Ys Origin have a 1.4GB patch so that wouldn't work.

**Comment by JK3Y** [comment]
Hmmm. I have a lot of physical games too (large LRG collection, unopened) and I've used NPS to DL the digital versions. pkg2zip should be generating the spoofed license like with any other game allowing nonpdrm to work as usual with livearea updates.

I just pushed out an update. I unfortunately didn't read your issue properly and this will have to be included in the next update (prob tomorrow or the next day. this weekend forsure.) I didn't notice you were on the PSV Updates category and I ended up adding the required_fw column to the PSV Games category. :/

I'm looking at the TSV for the updates and it appears that right now the second update listed in the updates list is always the newest one for that game / if you have it sorted differently, it's the largest of the updates for that particular title. I was also told when chatting with devs about how the compat pack updates will work and they said that all updates contain the previous updates issued for a title. You shouldn't have to download the updates that are released prior to the latest.

**Comment by craigerskine** [comment]
When I do the refresh thing on the unpatched game in the LiveArea, it spins for a few seconds and no update icon shows. I've had to manually download the patches.

Something must be wrong with my system.

I'm on the PSTV, and every few days I have to unplug the power and reboot because the system will not wake from standby. Something is definitely wonky.

Yeah, I understand the latest update file contains all previous... I just couldn't tell which one was the latest because there was no update version # in the meta data in the app. I looked at the file size for reference, but again, games like Ys Origin have multiple patches but the file size is the same (because I think they include the entire game). I also tried to use the second one listed but for Freedom Wars the second one was the older patch (probably because of the name change).

**Comment by JK3Y** [comment]
Hmmm. I don't have a PSTV so I'm unsure if there's anything different needed plugin-wise. I'm assuming all plugins are the latest releases on the PSTV? I know that storagemgr was updated recently that should solve that standby problem.

You're making good points and I'll definitely add this column in bc it seems pretty important lol.

tbqh, i forgot the charger for my macbook pro this morning before leaving the house so I can't just add it and push a new update right now :/

**Comment by JK3Y** [comment]
I just pushed a commit that adds this. When I have my charger in a bit I'll work on your other issue (#8) and get that working. Then I'll push out a new release. But it's available to build right now if you have XCode installed.

**Comment by craigerskine** [comment]
Awesome! Thanks so much for your help on this!

**Comment by JK3Y** [comment]
Added in commit 2d73eb6
