### ISSUE TITLE
1.3.6 insta-crashes after bookmarking

### ISSUE THREAD

**Issue by RaphaelDDL** [JK3Y/NPS-Browser-macOS#20]
Heya :)

Downloaded 1.3.6, did `rm -r ~/Library/Application\ Support/NPS\ Browser/` just to make sure. 

What I did:
- Open, got lots of dialogs about default preferences error
- Managed to open Preferences and Re-set-up all URLs, saved, fetched list
- Noticed my bookmarks were gone
- Went bookmark some again; I searched on PSV US `atelier`
- clicked on first, holded Shift and clicked on last (was trying to see if I could multi-select, cannot :P)
- with last selected (`Firis` I think), clicked on bookmark star
- clicking on the before last one, I noticed the bookmark was already yellow, I clicked again just to make sure
- App crashed

Tried opening multiple times, no luck. Selecting any of the two options in the dialog about opening windows does not do anything, app straight up crashes. RM'ing app support again does not help.

Here my crash dump: [NPS Browser_2018-08-03-024051_Raphaels-MacBook-Pro.crash.log](https://github.com/JK3Y/NPS-Browser-macOS/files/2256132/NPS.Browser_2018-08-03-024051_Raphaels-MacBook-Pro.crash.log)

Thanks for your hard work, bro :)

**Comment by JK3Y** [comment]
try deleting the user settings you have set:
`defaults delete JK3Y.NPS-Browser`
then rerun.

Does this make the app able to start? the error "Invalid path given: /Users/RaphaelDDL/Downloads/NPS Downloads/" makes me think it's the download folder's path that's the problem... I'll have to do more looking into this though.

**Comment by RaphaelDDL** [comment]
I never set that folder. My NPS folder (from previous versions) always was `~/Documents/NPS`. Before deleting the defaults, I created that folder you mentioned. The app opened as normal. O__o

I checked the preferences, the path indeed is wrong, though if I press the Folder icon, it shows me the correct place (inside Documents). So I clicked on my folder on Documents again and now the path updated. Weird.

I guess you'll need an error handler for when folder on settings do not exist. 

---

Well, just to make sure folder had nothing to do with the bookmark, I did the same steps just to make sure: search atelier, bookmarked Firis, the before last one - shallie - already have yellow star, crashed again (now with the folder).

But reopening does not crash instantly. What I noticed was that whenever I bookmark something, all games stay with yellow star, for example, I removed the search, went back to full list, all games are yellow star.

Doing the defaults delete didn't change anything.
[NPS Browser_2018-08-03-122814_Raphaels-MacBook-Pro.crash.log](https://github.com/JK3Y/NPS-Browser-macOS/files/2257899/NPS.Browser_2018-08-03-122814_Raphaels-MacBook-Pro.crash.log)

Bookmarking, closing, reopening. The bookmarked game has no yellow star. It shows on the Bookmark list though. Clicking on it's star toggle between white/yellow, but it's not added/removed from the list. Doing the same on other game crashes too.

**Comment by JK3Y** [comment]
Thanks for trying so many things, it narrowed it down for me. It seems like the issue is with the bookmarks and how they're being handled. Does the app crash for you if you don't use the bookmark star?

**Comment by RaphaelDDL** [comment]
Glad to be of help :)

**Comment by JK3Y** [comment]
I found the stupid issue. I accidentally deleted one of the functions that checks if the selected row has a bookmark then changes the star accordingly. -____________-

If you have XCode installed you can build from source, otherwise I'm gonna keep working on some other additions and will push out an update later.

**Comment by RaphaelDDL** [comment]
hahah no worries.
That's what git is good for, pulling out diffs to see what was wrong :D
