### ISSUE TITLE
Constant crash on start

### ISSUE THREAD

**Issue by Korsovich** [JK3Y/NPS-Browser-macOS#22]
I was adding code for the repositories so I could use this program. I got PSV tsv for games, dlc, themes.
Then I added pkg dec parameters -x {pkgFile} "{zRifKey}" --
Then CompPack URL: | https://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/entries.txt
CompPack Patch URL: | https://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/entries_patch.txt
 and closed the window and reloaded. It now crashes constantly and i cant access the settings to change any information. Its stuck in a loop and I removing the DMG and app and restarting does nothing. Has this issue come up yet?

**Comment by JK3Y** [comment]
Where are you putting the pkg2zip parameters? Those aren't needed. Those parameters are changed based on the selected options in Preferences:
<img width="373" alt="screen shot 2018-08-04 at 4 34 44 pm" src="https://user-images.githubusercontent.com/17938577/43680632-5754c44a-9804-11e8-9c67-0b578135efdb.png">

The only things that are needed by you are the URLs. You can try running the remove script from the Readme:
```
rm -r ~/Library/Application\ Support/NPS\ Browser/
rm -r ~/Library/Caches/JK3Y.NPS-Browser
defaults delete JK3Y.NPS-Browser
```

**Comment by Korsovich** [comment]
OMG Thank you! I couldn't find that file to delete and this worked perfect. 
I love you, you magnificent beast!
