### ISSUE TITLE
dlcs are tagged as "game" in download list

### ISSUE THREAD

**Issue by gatosardina** [JK3Y/NPS-Browser-macOS#23]
If i download a game it correctly tags it as game
if it has available updates, it tags it aas update
but if i download the dlc it tags them as game too
https://imgur.com/a/NAc54Rt

**Comment by gatosardina** [comment]
i think its because when you select any dlc, at the end of the right side panel there is a marked checkbox that reads "game"

**Comment by JK3Y** [comment]
That is actually exactly why it says 'game' for dlc. Game is just an umbrella category for the base file you're downloading. Maybe I should rename is 'base file' or just have it change based on file type. This doesn't affect the extraction process tho cause that's determined by console type
