### ISSUE TITLE
Setting to limit max number of concurrent downloads

### ISSUE THREAD

**Issue by RaphaelDDL** [JK3Y/NPS-Browser-macOS#3]
#### Add a new "Concurrent Downloads" (integer) in Preferences;

Reasoning: Used to limit the number of concurrent downloads, this way if any new download is added to the queue (more than the setting limit), it'll be on hold. Good for people with slow internet.

**Comment by JK3Y** [comment]
Added this in d33342f040797262d83a0ba33d33a2685f64b773. Was already in the works :)

**Comment by RaphaelDDL** [comment]
Nice, thanks @JK3Y :D
