### ISSUE TITLE
Settings/Preferences window is nearly unaccessible 

### ISSUE THREAD

**Issue by phJapan** [JK3Y/NPS-Browser-macOS#30]
![screen shot 2018-08-16 at 6 42 19 pm](https://user-images.githubusercontent.com/42435559/44201462-37e04600-a184-11e8-9e77-4afa9706e3b7.png)

Settings/Preferences window is about a 1/3rd of it's intended size. Size cannot be adjusted making it nearly impossible to work with. Was able to paste PSV link and bring up the PSV titles in main browser.

Using OS X Yosemite 10.10.5.

**Comment by JK3Y** [comment]
I'm working on getting an installer for Yosemite 10.10 so I can properly test for this build. I can upload a build that I have in development right now if you wanna test it really quick. The preferences window is complete redone

**Comment by Sir-Charles** [comment]
Ok cool, sure I'll test it. Also I was trying some things on OS X 10.10.5 and theres a few more issues, the downloads button isn't shown and I can't see DL progress at all, and the bookmarks window won't show either.

Also I was able to enter the links for PSX and PSV DLC by using shift+tab to move up text boxes, but after downloading something they wouldn't extract, just stay as pkg's.

And I have a question for comp pack patches, what link do I use? The app crashes when I refresh using the same one as comp pack:
"https://XXXXXX.com/nopaystation_repos/nps_compati_packs/raw/master/"

**Comment by JK3Y** [comment]
@Sir-Charles compat **Packs**: https://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/entries.txt

compat **Patch**: https://gitlab.com/nopaystation_repos/nps_compati_packs/raw/master/entries_patch.txt

I've gotten the screen to look as it should. 10.10 has autolayout issues... so the solution was to put a constraint on each UI element.

I was able to open the downloads and bookmarks on this build too.

![screen shot 2018-08-18 at 12 04 14 pm](https://user-images.githubusercontent.com/17938577/44301591-5870e300-a2df-11e8-9066-729aedebd0f2.png)

I have a couple more things I want to add to this release, then it'll be sent out.

**Comment by Sir-Charles** [comment]
AWESOME!!! Thanks for the work you put into this, making a NPS Browser for us Mac users, and not forgetting the people still on 10.10. I was just using the spreadsheet and pkg2zip before, but this has made things so much quicker and easier, I really appreciate it!
Can't wait for 1.4.2, keep up the good work!
