### ISSUE TITLE
Download list (and downloaded progress) lost after App crash

### ISSUE THREAD

**Issue by RaphaelDDL** [JK3Y/NPS-Browser-macOS#4]
First, nice work JK3Y, thank you for spending time building this 👍 

I've set multiple downloads and the app crashed. When opened again, download list was gone, had to re-add the queue. And of course, it started from 0% again.

Would be nice to save the downloaded bytes into a placeholder file on the system (with downloaded byte array) so if anything happens (closed app by mistake, crashed, etc), it could resume.

Here's my crash log, not sure if would help:

1.0 [Swift NPS Browser_2018-06-15-202042_Raphaels-MacBook-Pro.crash.log](https://github.com/JK3Y/NPS-Browser-macOS/files/2107816/Swift.NPS.Browser_2018-06-15-202042_Raphaels-MacBook-Pro.crash.log)

1.1 [Swift NPS Browser_2018-06-16-000236_Raphaels-MacBook-Pro.crash.log](https://github.com/JK3Y/NPS-Browser-macOS/files/2107833/Swift.NPS.Browser_2018-06-16-000236_Raphaels-MacBook-Pro.crash.log)

Thank you.

**Comment by JK3Y** [comment]
Stopping and resuming downloads was added last night in https://github.com/JK3Y/NPS-Browser-macOS/commit/d33342f040797262d83a0ba33d33a2685f64b773#diff-10af17ccd0bd157ec5c04405057c09db saving the list on exit is my next task

**Comment by JK3Y** [comment]
Download list is now restorable after app exit. 64132332432794a920d205e6702acacf35f306d6
Included in release v1.2.2!
