### ISSUE TITLE
Extract PKG after downloading setting is ignored

### ISSUE THREAD

**Issue by einsteinx2** [JK3Y/NPS-Browser-macOS#40]
I just noticed this while writing the other ticket. I actually don't want them extracted, however I noticed that the option was enabled (possibly by default?) and none of my pkg files are extracting after download.

**Comment by JK3Y** [comment]
@einsteinx2 I was just able to download a .pkg without extracting. It also downloaded the associated Update .pkg and compat packs all without extracting them.

If you could let me know what version of macOS you're using, that would help narrow down the issue. I know that running in Yosemite can be buggy since Apple changed some of the APIs used between v10.10 and 10.11+

**Comment by einsteinx2** [comment]
I'm able to download without extracting, what I meant was that even with that option checked, they don't extract either.

I'm on the latest Mojave beta, so its's possible that has to do with it.

**Comment by JK3Y** [comment]
@einsteinx2 Hmm possibly... I just downloaded and extracted Bloodstained: Curse of the Moon base game/update/comp packs. Could you check if there's any logs? They should be in `~/Library/Logs/DiagnosticReports`. There's also a log in `~/Library/Caches/NPS Browser`. I'm going to be putting out a new release today that fixes a bunch of issues (#37, #38, #41, and #43). 

#39 and this issue will have to wait until I can get a copy of Mojave working. I tried installing Public Beta 6 and it froze up my computer to the point that I had to format my HD and restore from Time Machine. Not really wanting to mess around with it again until official release... But I'll see if I can get a copy working inside Parallels or something.

**Comment by JK3Y** [comment]
I'm going to go ahead and close this. I was able to download/extract all files downloaded from NPS in macOS Mojave. Send in some error logs so I can see what the problem was, bc it doesn't look like it's Mojave.
