### ISSUE TITLE
App crashes if previously set download folder is deleted

### ISSUE THREAD

**Issue by andecoder** [JK3Y/NPS-Browser-macOS#50]
**Describe the bug**
The app crashes on launch if the previously set 'Download location' doesn't exist

**To Reproduce**
1. Take note of the currently set 'Download location', or change it to something new
2. Close the app
3. Delete (or rename) the folder that is set as the 'Download location'
4. Open the app again

**Expected behavior**
App should not crash if the set 'Download location' doesn't exist

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Version 10.14.2

**Additional context**
Maybe ask for a new location if previously set location is invalid, or set it to the 'Downloads' folder

**Comment by metaColin** [comment]
I am encountering the same bug. One cannot change the download location from it's initial path without inducing a crash on attempted download.

**Comment by JK3Y** [comment]
This has been fixed in the latest version
