### ISSUE TITLE
NPS-Browser-Windows 

### ISSUE THREAD

**Issue by EmulationChannel** [JK3Y/NPS-Browser-macOS#56]
NSP-Browser Fron Windows some forecast for arrivals

**Comment by TheRadziu** [comment]
its already a thing, and in fact came way before mac one did. 

check NPS website for download and source code.

**Comment by EmulationChannel** [comment]
@TheRadziu Link Site Download ?

**Comment by JK3Y** [comment]
@EmulationChannel I'm not sure what you're asking, but the browser app for Windows is here http://nopaystation.com/vita/npsReleases/
