### ISSUE TITLE
Application crash when downloading to external  usb SSD  on Mac

### ISSUE THREAD

**Issue by sokzkota** [JK3Y/NPS-Browser-macOS#58]
**Describe the bug**
When in preferences I set external SSD, app will crash - it only creates Folder NPS Downloads

**To Reproduce**
1.Set external drive in prefernces (/Volumes/Samsung T5/NPS Downloads)
2.Try to download any vita game at all
 
**Expected behavior**
Game should download

** report**
Process:               NPS Browser [2019]
Path:                  /Applications/NPS Browser.app/Contents/MacOS/NPS Browser
Identifier:            JK3Y.NPS-Browser
Version:               1.4.3 (67)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           NPS Browser [2019]
User ID:               501

Date/Time:             2019-06-08 18:04:25.322 +0200
OS Version:            Mac OS X 10.14.5 (18F132)
Report Version:        12
Anonymous UUID:        D702BB28-3302-7A69-74CE-C61E0A59585E

Sleep/Wake UUID:       B184FD79-1F55-4E64-82E8-70941A02035A

Time Awake Since Boot: 26000 seconds
Time Since Wake:       5200 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007ffeec560ff0
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [2019]

VM Regions Near 0x7ffeec560ff0:
    MALLOC_TINY            00007fc0f6000000-00007fc0f6300000 [ 3072K] rw-/rwx SM=PRV  
--> STACK GUARD            00007ffee8d61000-00007ffeec561000 [ 56.0M] ---/rwx SM=NUL  stack guard for thread 0
    Stack                  00007ffeec561000-00007ffeecd61000 [ 8192K] rw-/rwx SM=SHM  thread 0

Application Specific Information:
Performing @selector(btnDownloadClicked:) from sender NSButton 0x600002edd290

**Desktop (please complete the following information):**
 - OS: MAcOS Mojave
 - Browser N/A
 - Version 1.4.3(67)

**Additional context**

**Comment by JK3Y** [comment]
This has been fixed in the latest version
