### ISSUE TITLE
Wrong tag for PSV Themes renders option unusable

### ISSUE THREAD

**Issue by AnalogMan151** [JK3Y/NPS-Browser-macOS#61]
Currently if you try to use the PSV Themes menu option you get an error message stating no PSV Update URL is set. This is because the PSV Themes menu is set as tag 3 as shown here:

https://github.com/JK3Y/NPS-Browser-macOS/blob/c80f458d0c155d766a454deae6a579919c599ad1/NPS%20Browser/Base.lproj/Main.storyboard#L600

However tag 3 is Updates, not Themes.

https://github.com/JK3Y/NPS-Browser-macOS/blob/c80f458d0c155d766a454deae6a579919c599ad1/NPS%20Browser/models/ItemType.swift#L35-L38

Looks like the tag for PSV Themes should be 2, not 3.

**Comment by JK3Y** [comment]
Ah, thank you for finding this. I will put out a new release soon.
