### ISSUE TITLE
NPS Browser (macOS) RAP Files = 404.html

### ISSUE THREAD

**Issue by garretts228** [JK3Y/NPS-Browser-macOS#64]
I have tried V 1.4.4 and V 1.4.5 and both fail to download any RAP files. It downloads the package file fine, but it appears to generate a 404.html file instead of a RAP file. Also, not sure if this is a bug, but on windows it names the package file with the name of the game. On macOS the package file is just a bunch of random numbers and letters.  Thanks for your work!

**Comment by derekelliott01** [comment]
have you fixed issue?

**Comment by JK3Y** [comment]
Check the new v1.4.6 release

**Comment by kevinwt95** [comment]
I use the new 1.4.6 and still getting 404.html
