### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by RobertoD91** [JK3Y/NPS-Browser-macOS#65]
It would be nice to install NPS Browser from brew or brek cask.

**Comment by JK3Y** [comment]
this isn't an NPS Browser issue. feel free to issue a PR to homebrew-cask, though i doubt they'd approve it.

https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
