### ISSUE TITLE
can't open the bookmarks "library"

### ISSUE THREAD

**Issue by gatosardina** [JK3Y/NPS-Browser-macOS#7]
might be an issue with the new and upcoming macos 10.14 update
when i click on the open book button, the bookmarks library doesnt open
if i keep clicking it repeatedly, it will open for a second, before turning invisible

**Comment by gatosardina** [comment]
here i left a screen recording https://imgur.com/a/zaRP9Bs

**Comment by gatosardina** [comment]
the issue seemed to fix by itself after a few days and i havent seen it happen again, so im going to close the issue

**Comment by JK3Y** [comment]
I've experience this problem myself but only when testing via xcode. It isn't consistent and there doesn't seem to be anything that explicitly triggers the popovers to behave this way. Usually restarting the app fixes the issue for me. I'm glad it cleared up for you
