### ISSUE TITLE
Local Game Lists (TSV)

### ISSUE THREAD

**Issue by craigerskine** [JK3Y/NPS-Browser-macOS#8]
Is there a way to use local .tsv files instead of relying on the live NPS site. The Windows version allows for either type. This would be a nice-to-have in case the NPS site goes down, moves, etc.

**Comment by JK3Y** [comment]
Yeah this is definitely possible, I'll work on implementing it.

**Comment by JK3Y** [comment]
Haven't quite figured out how to do this yet, but I am working on it!

**Comment by JK3Y** [comment]
The problem I'm having with this is determining if the text is a local file or if it's a URL. I've been trying to get it to determine it's a local file by using the scheme "/Users/USER/Folder/FILE.tsv" but it doesn't like that. My other option is to have it displayed as "file:///Users/USER/Folder/FILE.tsv" but I don't think that looks as good, however it may be my only solution.

Will test this, and if it works this solution will be the one implemented.

**Comment by JK3Y** [comment]
Added in commit 2d73eb6
