### ISSUE TITLE
Resuming downloads doesn't work

### ISSUE THREAD

**Issue by dhondup2** [JK3Y/NPS-Browser-macOS#9]
When downloading if it's stopped and then resumed it starts the download and then it doesn't extract the file but instead gives me an error "Failed! Optional(Alamofire.AFError.response" after reaching 100%. Does anyone have this issue?
<img width="844" alt="screen shot 2018-07-20 at 7 26 02 am" src="https://user-images.githubusercontent.com/32646210/43002586-efd145b2-8bee-11e8-8f3b-9fcd01a815be.png">

**Comment by JK3Y** [comment]
Thank you, I'll look into this!

**Comment by JK3Y** [comment]
This has been fixed as of commit 2e02ee8.
